services:

  elasticsearch:
    build:
      context: ../Elasticsearch
      dockerfile: Dockerfile.elasticsearch
    image: custom-elasticsearch-with-plugin
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
    networks:
      - prod_server
    restart: unless-stopped

#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.12.0
#    container_name: kibana
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    volumes:
#      - ./volumes/kibana-data:/usr/share/kibana/data
#    depends_on:
#      - elasticsearch
#    networks:
#      - prod_server
#    restart: unless-stopped


  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    ports:
      - "5000:5000"
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - ./http/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./http/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ../logs:/logs
    depends_on:
      - elasticsearch
    networks:
      - prod_server
    restart: unless-stopped

networks:
  prod_server:
    external: true
