# AWS 용 docker-compose

services:
  redis:
    container_name: redis_noise
    image: 'redis:latest'
    ports:
      - "6379:6379"
    networks:
      - prod_server
    restart: unless-stopped


networks:
  prod_server:
    external: true

