apiVersion: batch/v1
kind: CronJob
metadata:
  name: noisense-batch-job
spec:
  schedule: "30 9,15 * * *"      # 매일 9시 30분, 15시 30분에 실행 -> 오전에 api data 업데이트가 안되어있을 시 오후에 한 번 더 확인하기위해 15시 30분에도 실행
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: noisense-batch
              image: registry.dosion.com/noisense/backend-batch:1.0.0  # 빌드한 이미지 태그
              args:
                - --spring.profiles.active=local
                - --job.name=hourlyNoiseJob
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: local
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 2  # 완료된 Job 이력 유지 수
  failedJobsHistoryLimit: 1      # 실패한 Job 이력 유지 수
