# dev 환경 설정
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://dev-db.example.com:5432/noisense
    username: noisense_dev
    password: dev_pw


  # JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# 로깅
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG


---


# OAuth2 설정 예시 (공통 또는 프로파일별로 나눠도 됨)
# 우선 미사용 처리
spring:
  security:
    oauth2:
      client:
        registration: {}
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
#            scope:
#              - profile
#              - email
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
#            user-name-attribute: sub

