# batch 환경 설정
spring:
  config:
    activate:
      on-profile: batch
  docker:
    compose:
      enabled: false


  # JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: noisense
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # jdbc batch size 설정
        jdbc:
          batch_size: 500
    show_sql: true

  # batch
  batch:
    job:
      enabled: false

# 로깅
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
